"""Simulation of iter23-like PEP logic with and without the agg_bid take.

This mimics iter23's PEP behavior simplified (ignore take_sig defensive widen):
- Take any ask < fv_int
- If pos < 70: fast accumulate (buy all asks up to fv_int+6, then post bid at bb+1)
- If pos >= 70: post bid at min(bb+1, fv_int-1), post sell 8 at max(ba-1, fv_int+1)

Then ADD: take any aggressive bid (bp >= floor(FV)) for as much as short-cap allows.
Compare end-of-day PnL with and without the addition.

Fills are generated by matching our orders against the CSV book.
Posted orders "rest" one tick; next tick, they're matched against the new book's
trades (approx: treat them as filled if a trade in next tick crosses our price).

This is a lightweight simulator — not the IMC engine. Use it for relative comparison,
not absolute PnL.
"""
from __future__ import annotations
import pathlib
import numpy as np
import pandas as pd

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "ROUND_2"


def load(day: int):
    p = pd.read_csv(DATA / f"prices_round_2_day_{day}.csv", sep=";")
    t = pd.read_csv(DATA / f"trades_round_2_day_{day}.csv", sep=";")
    p = p[p["product"] == "INTARIAN_PEPPER_ROOT"].sort_values("timestamp").reset_index(drop=True)
    t = t[t["symbol"] == "INTARIAN_PEPPER_ROOT"].sort_values("timestamp").reset_index(drop=True)
    return p, t


def fv_day(day: int, ts: np.ndarray) -> np.ndarray:
    day_start = {-1: 11000, 0: 12000, 1: 13000}[day]
    return day_start + 0.1 * (ts // 100)


def bb_ba(row):
    bid = row["bid_price_1"]
    ask = row["ask_price_1"]
    return (int(bid) if pd.notna(bid) else None, int(ask) if pd.notna(ask) else None)


def step_book_bids_asks(row):
    bids, asks = {}, {}
    for k in (1, 2, 3):
        bp = row[f"bid_price_{k}"]; bv = row[f"bid_volume_{k}"]
        ap = row[f"ask_price_{k}"]; av = row[f"ask_volume_{k}"]
        if pd.notna(bp): bids[int(bp)] = int(bv)
        if pd.notna(ap): asks[int(ap)] = int(av)
    return bids, asks


def simulate_pep(day: int, take_agg_bid: bool = False, agg_bid_min_pos: int = 50) -> dict:
    """
    agg_bid_min_pos: only fire agg_bid take when pos >= threshold (to avoid conflict
    with fast-accumulate). Set to 0 to always fire.
    """
    p, trades = load(day)
    fv = fv_day(day, p["timestamp"].values)
    fv_int = np.round(fv).astype(int)
    floor_fv = np.floor(fv).astype(int)
    LIMIT = 100

    cash = 0.0
    position = 0
    my_orders_next = []  # list of (price, qty) posted this tick, executed next tick

    n = len(p)
    for i in range(n):
        row = p.iloc[i]
        bids, asks = step_book_bids_asks(row)
        bb, ba = bb_ba(row)
        fi = fv_int[i]
        ff = floor_fv[i]

        # ─── Execute resting orders from previous tick ───────────────
        # Match against this tick's book. Buy order at price p fills if any ask <= p.
        # Sell order at price p fills if any bid >= p.
        executed = []
        for (op, oq) in my_orders_next:
            if oq > 0:  # buy
                # fills against asks <= op
                filled = 0
                for ap_px in sorted(asks):
                    if ap_px > op or filled >= oq: break
                    avail = asks[ap_px]
                    take = min(avail, oq - filled)
                    if take > 0:
                        cash -= ap_px * take
                        position += take
                        filled += take
                if filled > 0:
                    executed.append((op, filled))
            else:  # sell
                need = -oq
                filled = 0
                for bp_px in sorted(bids, reverse=True):
                    if bp_px < op or filled >= need: break
                    avail = bids[bp_px]
                    take = min(avail, need - filled)
                    if take > 0:
                        cash += bp_px * take
                        position -= take
                        filled += take
                if filled > 0:
                    executed.append((op, -filled))
        my_orders_next = []

        # ─── iter23-like take-ask (takes any ask < fv_int) ──────────
        for apx in sorted(asks.keys()):
            if apx >= fi: break
            avail = asks[apx]
            cap = LIMIT - position
            if cap <= 0: break
            q = min(avail, cap)
            if q > 0:
                cash -= apx * q
                position += q
                asks[apx] -= q

        # ─── NEW: take aggressive bid (sell at bid >= floor(FV)) ─────
        if take_agg_bid and position >= agg_bid_min_pos:
            for bpx in sorted(bids.keys(), reverse=True):
                if bpx < ff: break   # only aggressive (bid >= floor(FV))
                avail = bids[bpx]
                cap = LIMIT + position  # short capacity
                if cap <= 0: break
                q = min(avail, cap)
                if q > 0:
                    cash += bpx * q
                    position -= q
                    bids[bpx] -= q

        # ─── iter23-like quoting ────────────────────────────────────
        # Fast-accumulate: pos<70: buy through asks up to fi+6
        if position < 70:
            buy_limit = fi + 6
            for apx in sorted(asks.keys()):
                if apx > buy_limit or apx < fi: continue
                avail = asks[apx]
                cap = LIMIT - position
                if cap <= 0: break
                q = min(avail, cap)
                if q > 0:
                    cash -= apx * q
                    position += q
                    asks[apx] -= q
            remaining = LIMIT - position
            if remaining > 0 and bb is not None:
                my_orders_next.append((bb + 1, remaining))
        else:
            buy_cap = LIMIT - position
            if buy_cap > 0 and bb is not None:
                bid_px = min(bb + 1, fi - 1)
                my_orders_next.append((bid_px, buy_cap))
            sell_qty = min(8, LIMIT + position)
            if sell_qty > 0:
                ask_px = max(ba - 1, fi + 1) if ba is not None else fi + 7
                my_orders_next.append((ask_px, -sell_qty))

    # Flush remaining orders at final mid
    final_mid = (p["bid_price_1"].iloc[-1] + p["ask_price_1"].iloc[-1]) / 2
    final_fv = fv[-1]

    mtm_mid = cash + position * final_mid
    mtm_fv = cash + position * final_fv
    return dict(day=day, cash=cash, position=position, mtm_mid=mtm_mid, mtm_fv=mtm_fv,
                final_mid=final_mid, final_fv=final_fv)


def main() -> None:
    print("=" * 100)
    print("iter23-like PEP simulator — with and without agg_bid take")
    print("=" * 100)

    for label, use_agg, min_pos in [
        ("baseline (iter23-like)", False, 50),
        ("+agg_bid take, pos>=50", True, 50),
        ("+agg_bid take, pos>=70", True, 70),
        ("+agg_bid take, pos>=0 (unconditional)", True, 0),
    ]:
        total_fv = 0
        total_mid = 0
        detail = []
        for day in (-1, 0, 1):
            r = simulate_pep(day, take_agg_bid=use_agg, agg_bid_min_pos=min_pos)
            detail.append(r)
            total_fv += r["mtm_fv"]
            total_mid += r["mtm_mid"]
        print(f"\n{label}")
        for r in detail:
            print(f"  day {r['day']}: cash={r['cash']:+10.0f}  pos={r['position']:+4d}  MTM_mid={r['mtm_mid']:+10.0f}  MTM_fv={r['mtm_fv']:+10.0f}")
        print(f"  TOTAL 3-day MTM_fv={total_fv:+.0f}  MTM_mid={total_mid:+.0f}  avg/day={total_fv/3:+.0f}")


if __name__ == "__main__":
    main()
