#!/usr/bin/env python3
"""Produce docs/round2_log_analysis/submissions_table.md from parsed logs.

Usage:
    python3 compare_submissions.py all
    python3 compare_submissions.py 294069 241988 108517
    python3 compare_submissions.py --since 236000     # only sub_ids >= 236000

Caches each parse at docs/round2_log_analysis/parsed/<sub>.json so re-runs
are cheap. Pass --refresh to force re-parsing.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
DOCS_DIR = REPO_ROOT / "docs" / "round2_log_analysis"
PARSED_DIR = DOCS_DIR / "parsed"
TABLE_PATH = DOCS_DIR / "submissions_table.md"
LOGS_ROOT = Path("/tmp/prosperity_logs")

sys.path.insert(0, str(SCRIPT_DIR))
from parse_log import _parse_one, resolve_submission_log  # noqa: E402


def list_submissions_with_logs() -> list[str]:
    out: list[str] = []
    for entry in LOGS_ROOT.iterdir():
        if not entry.is_dir():
            continue
        if not entry.name.isdigit():
            continue
        if any(f.suffix == ".log" for f in entry.iterdir()):
            out.append(entry.name)
    # Sort numerically
    out.sort(key=int)
    return out


def _parsed_path(sub_id: str) -> Path:
    return PARSED_DIR / f"{sub_id}.json"


def get_parsed(sub_id: str, refresh: bool = False) -> dict[str, Any] | None:
    """Load cached parse, or parse fresh if missing / stale / refresh."""
    cache = _parsed_path(sub_id)
    try:
        log_path = resolve_submission_log(sub_id)
    except FileNotFoundError:
        return None
    log_mtime = log_path.stat().st_mtime
    if not refresh and cache.exists() and cache.stat().st_mtime >= log_mtime:
        try:
            return json.loads(cache.read_text())
        except Exception:
            pass
    record = _parse_one(log_path)
    cache.parent.mkdir(parents=True, exist_ok=True)
    cache.write_text(json.dumps(record, indent=2, sort_keys=True))
    return record


def _fmt(v: Any, spec: str = "") -> str:
    if v is None:
        return "-"
    if isinstance(v, bool):
        return "Y" if v else "N"
    if isinstance(v, (int, float)):
        try:
            return format(v, spec) if spec else str(v)
        except (ValueError, TypeError):
            return str(v)
    return str(v)


def _delta(curr: float | None, prev: float | None) -> str:
    if curr is None or prev is None:
        return "-"
    d = curr - prev
    sign = "+" if d >= 0 else ""
    return f"{sign}{d:,.2f}"


def build_rows(sub_ids: list[str], refresh: bool) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for sid in sub_ids:
        record = get_parsed(sid, refresh=refresh)
        if record is None:
            rows.append({"submission_id": sid, "_missing": True})
            continue
        rows.append(record)
    # Sort by timestamp (submission time) asc
    rows.sort(key=lambda r: r.get("timestamp", 0))
    return rows


def render_table(rows: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("# Round 2 — submissions table")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/log_analysis/compare_submissions.py`. "
        "One row per server submission, sorted by submission time. "
        "`Δ$/tick` is vs the previous row in this table."
    )
    lines.append("")
    lines.append(
        "`PL hits` = total sandbox position-limit breach messages across products. "
        "`Tox` = mean adverse-mid-move 5 ticks after each SUBMISSION fill, "
        "across both products; positive = on-average filled before price moved against us."
    )
    lines.append("")
    header = (
        "| # | sub_id | run_id | date | ticks | total $ | $/tick | Δ$/tick | "
        "fills | fill rate | PL hits | Tox (osm) | Tox (pep) | errors |"
    )
    sep = "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"
    lines.append(header)
    lines.append(sep)

    prev_pt: float | None = None
    import datetime as _dt
    for i, r in enumerate(rows, 1):
        if r.get("_missing"):
            lines.append(
                f"| {i} | {r['submission_id']} | - | - | - | - | - | - | - | - | - | - | - | (no log) |"
            )
            continue
        ts = r.get("timestamp")
        date_s = _dt.datetime.fromtimestamp(ts).strftime("%m-%d %H:%M") if ts else "-"
        pt = r.get("per_tick_pnl")
        delta = _delta(pt, prev_pt)
        prev_pt = pt
        pp = r.get("per_product", {})
        osm = pp.get("ASH_COATED_OSMIUM", {})
        pep = pp.get("INTARIAN_PEPPER_ROOT", {})
        pl_hits = sum(
            d.get("position_limit_hits", 0) or 0 for d in pp.values()
        )
        errs = r.get("any_errors") or []
        err_s = (
            "-" if not errs
            else f"{sum(e.get('count', 1) for e in errs)} ({len(errs)} unique)"
        )
        lines.append(
            "| {i} | {sub} | {run} | {date} | {ticks} | {total:,.2f} | "
            "{pt:.3f} | {delta} | {fills} | {fr:.1%} | {pl} | "
            "{tox_osm} | {tox_pep} | {err} |".format(
                i=i,
                sub=r["submission_id"],
                run=r.get("run_id", "-"),
                date=date_s,
                ticks=_fmt(r.get("total_ticks")),
                total=r.get("total_pnl") or 0,
                pt=pt or 0,
                delta=delta,
                fills=_fmt(r.get("total_fills")),
                fr=r.get("fill_rate") or 0,
                pl=pl_hits,
                tox_osm=_fmt(osm.get("largest_adverse_move_after_fill"), ".2f"),
                tox_pep=_fmt(pep.get("largest_adverse_move_after_fill"), ".2f"),
                err=err_s,
            )
        )
    lines.append("")
    lines.append("## Per-product PnL")
    lines.append("")
    lines.append("| # | sub_id | osm $ | osm $/tick | osm fills | pep $ | pep $/tick | pep fills |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for i, r in enumerate(rows, 1):
        if r.get("_missing"):
            continue
        pp = r.get("per_product", {})
        osm = pp.get("ASH_COATED_OSMIUM", {})
        pep = pp.get("INTARIAN_PEPPER_ROOT", {})
        lines.append(
            "| {i} | {sub} | {osm_pnl} | {osm_pt} | {osm_f} | {pep_pnl} | {pep_pt} | {pep_f} |".format(
                i=i,
                sub=r["submission_id"],
                osm_pnl=_fmt(osm.get("pnl"), ",.2f"),
                osm_pt=_fmt(osm.get("per_tick_pnl"), ".3f"),
                osm_f=_fmt(osm.get("num_fills")),
                pep_pnl=_fmt(pep.get("pnl"), ",.2f"),
                pep_pt=_fmt(pep.get("per_tick_pnl"), ".3f"),
                pep_f=_fmt(pep.get("num_fills")),
            )
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("submissions", nargs="*", help="submission_ids, or 'all'")
    ap.add_argument("--since", type=int, help="only submissions with id >= this")
    ap.add_argument("--refresh", action="store_true", help="re-parse even if cached")
    ap.add_argument("--out", help="override output path")
    ap.add_argument("--stdout", action="store_true", help="print table to stdout instead of writing")
    args = ap.parse_args()

    if not args.submissions or args.submissions == ["all"]:
        sub_ids = list_submissions_with_logs()
    else:
        sub_ids = args.submissions
    if args.since is not None:
        sub_ids = [s for s in sub_ids if s.isdigit() and int(s) >= args.since]
    if not sub_ids:
        print("No submissions selected", file=sys.stderr)
        return 1

    rows = build_rows(sub_ids, refresh=args.refresh)
    table = render_table(rows)

    if args.stdout:
        print(table)
    else:
        out_path = Path(args.out) if args.out else TABLE_PATH
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(table)
        print(f"wrote {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
